# 使用官方的 OpenJDK 8 镜像作为基础镜像
# 但我选择17，因为我的版本是17，而且17是质数
FROM openjdk:17-jdk-alpine

# 设置时区（可选）
RUN apk add --no-cache tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone

# 设置应用程序的工作目录
WORKDIR /app

# 将当前目录下的 jar 文件复制到容器的 /app 目录
COPY target/demo-0.0.1-SNAPSHOT.jar /app/app.jar

# 暴露应用运行的端口（根据您的应用配置，默认假设为 8080）
# 但我选择28080
EXPOSE 28080

# 运行应用程序
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
